### Get Method 
GET  http://localhost:5137/api/user/ HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1laWQiOiI3NjZmODJiZi0yZmRkLTQ2NmEtYTYxNy1jNjc1YWY3YmViNzciLCJyb2xlIjoiVXNlciIsIm5iZiI6MTcwMjc0MTI1NSwiZXhwIjoxNzAyOTE0MDU1LCJpYXQiOjE3MDI3NDEyNTUsImlzcyI6Ikhhc2FuIiwiYXVkIjoiaHR0cHM6Ly9qb3lkaXBrYW5qaWxhbC5jb20vIn0.epkxiQjmAwzGTIwchFc8Z-6lhfSqDwq2UskAzqAKvmQ

### Post Method
POST http://localhost:5137/api/user/ HTTP/1.1
Content-Type: application/json

{
    "firstName": "Admin",
    "lastName": "edge",
    "email": "adminas@email.com",
    "password": "nokia6300",
    "avatar": "https://yt3.googleusercontent.com",
    "address": "otavantie 20 a 15",
    "zip": "01450",
    "city": "vantaa"
}

### Delete method 
DELETE   http://localhost:5137/api/user/fe9e66fa-fc0e-470c-882b-44f4661ee63b HTTP/1.1
content-type: application/json


### Update method 
PUT  http://localhost:5137/api/user/254b6ab4-2cff-4878-85ab-6a2ca95d9b65 HTTP/1.1
Content-Type: application/json

{
    "firstName": "bassssand",
    "lastName": "edge",
    "email": "hasssan@email.com",
    "password": "nokia6300",
    "avatar": "https://yt3.googleusercontent.com",
    "address": "otavantie 20 a 15",
    "zip": "01xa550",
    "city": "vantxaa"
}


### Post Method
POST http://localhost:5137/api/auth HTTP/1.1
Content-Type: application/json

{
    "email": "haasan@email.com",
    "password": "nokia6300"
}