### Get Method 
GET  http://localhost:5137/api/user/ HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1laWQiOiJkZjlmZTBiOC1mNjM4LTQ2MjYtYTA3Zi02Mzk3Y2VmODRiZTAiLCJyb2xlIjoiQWRtaW4iLCJuYmYiOjE3MDI3NDU1MjYsImV4cCI6MTcwMjkxODMyNiwiaWF0IjoxNzAyNzQ1NTI2LCJpc3MiOiJIYXNhbiIsImF1ZCI6Imh0dHBzOi8vam95ZGlwa2FuamlsYWwuY29tLyJ9.1LQf2jgTFr_PmvwdCCtZe-_4Mf3Jf0w_ax6cGcoqIoI

### Post Method
POST http://localhost:5137/api/user/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1laWQiOiI3NjZmODJiZi0yZmRkLTQ2NmEtYTYxNy1jNjc1YWY3YmViNzciLCJyb2xlIjoiVXNlciIsIm5iZiI6MTcwMjc0MTI1NSwiZXhwIjoxNzAyOTE0MDU1LCJpYXQiOjE3MDI3NDEyNTUsImlzcyI6Ikhhc2FuIiwiYXVkIjoiaHR0cHM6Ly9qb3lkaXBrYW5qaWxhbC5jb20vIn0.epkxiQjmAwzGTIwchFc8Z-6lhfSqDwq2UskAzqAKvmQ

{
    "firstName": "Admin",
    "lastName": "edge",
    "email": "adminass@email.com",
    "password": "nokia6300",
    "avatar": "https://yt3.googleusercontent.com",
    "address": "otavantie 20 a 15",
    "zip": "01450",
    "city": "vantaa"
}

### Delete method 
DELETE   http://localhost:5137/api/user/fe9e66fa-fc0e-470c-882b-44f4661ee63b HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1laWQiOiI3NjZmODJiZi0yZmRkLTQ2NmEtYTYxNy1jNjc1YWY3YmViNzciLCJyb2xlIjoiVXNlciIsIm5iZiI6MTcwMjc0NTM5NywiZXhwIjoxNzAyOTE4MTk3LCJpYXQiOjE3MDI3NDUzOTcsImlzcyI6Ikhhc2FuIiwiYXVkIjoiaHR0cHM6Ly9qb3lkaXBrYW5qaWxhbC5jb20vIn0.kjvRv_Puvh8WqbwaSkNTK1OUBUJY25ie1_lssw2-kF0


### Update method 
PATCH   http://localhost:5137/api/user/766f82bf-2fdd-466a-a617-c675af7beb77 HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1laWQiOiI3NjZmODJiZi0yZmRkLTQ2NmEtYTYxNy1jNjc1YWY3YmViNzciLCJyb2xlIjoiVXNlciIsIm5iZiI6MTcwMjc0NTU4OCwiZXhwIjoxNzAyOTE4Mzg4LCJpYXQiOjE3MDI3NDU1ODgsImlzcyI6Ikhhc2FuIiwiYXVkIjoiaHR0cHM6Ly9qb3lkaXBrYW5qaWxhbC5jb20vIn0.BogTEh3wvR1MxkP6YxpqNhNvBuXu8dEQO59TlWh2-Wk

{
    "firstName": "basand",
    "lastName": "edge",
    "email": "hasssan@email.com",
    "password": "nokia6300",
    "avatar": "https://yt3.googleusercontent.com",
    "address": "otavantie 20 a 15",
    "zip": "01xa550",
    "city": "vantxaa"
}


### Post Method
POST http://localhost:5137/api/auth HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1laWQiOiI3NjZmODJiZi0yZmRkLTQ2NmEtYTYxNy1jNjc1YWY3YmViNzciLCJyb2xlIjoiVXNlciIsIm5iZiI6MTcwMjc0MTI1NSwiZXhwIjoxNzAyOTE0MDU1LCJpYXQiOjE3MDI3NDEyNTUsImlzcyI6Ikhhc2FuIiwiYXVkIjoiaHR0cHM6Ly9qb3lkaXBrYW5qaWxhbC5jb20vIn0.epkxiQjmAwzGTIwchFc8Z-6lhfSqDwq2UskAzqAKvmQ

{
    "email": "haasan@email.com",
    "password": "nokia6300"
}