version: '3'

services:
  # ilh-frontend service
  ilh-frontend:
    image: hasanmd91/ilh-frontend
    ports:
      - '3000:3000'

  # ilh-server service
  ilh-server:
    image: docker.io/library/ilh-server
    ports:
      - '8088:8088'
networks:
  dev:
    driver: bridge
