version: '3.8'

networks:
  dev:
    driver: bridge

services:
  # ilh-frontend

  ilh-frotend:
    image: hasanmd91/ilh-frontend
    environment:
      - REACT_APP_URL=http://localhost:8088/api/
    ports:
      - '3000:3000'

  # ilh-backend
  ilh-server:
    image: docker.io/library/ilh-server
    depends_on:
      - postgres
    container_name: ilh-backend
    ports:
      - '8088:8088'
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - ConnectionStrings__LocalDb=Host=localhost;Database=Ecom;Username=postgres;Password=postgres
      - ASPNETCORE_URLS=http://+:8088
      - DB_CONNECTION_POOL_SIZE=20
    networks:
      - dev

  # app_db service using postgres image
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_DB: Ecom
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - '5433:5432'
    restart: always
    volumes:
      - app_data:/var/lib/postgresql/data
    networks:
      - dev

volumes:
  app_data:
