### Get Method 
GET  http://localhost:5137/api/category/ HTTP/1.1
content-type: application/json


### Post Method 
POST http://localhost:5137/api/category/ HTTP/1.1
Content-Type: application/json

{
    "name": "Mjgkassh"
}


### Post Method 
GET http://localhost:5137/api/category/2b2f8057-2b8b-46a8-a93f-7f2f384267df HTTP/1.1
Content-Type: application/json



### Post Method 
DELETE  http://localhost:5137/api/category/2b2f8057-2b8b-46a8-a93f-7f2f384267df HTTP/1.1
Content-Type: application/json



### Patch Method 
PATCH http://localhost:5137/api/category/2b2f8057-2b8b-46a8-a93f-7f2f384267df HTTP/1.1
Content-Type: application/json

{
    "name": "Electronics"
}