### Get Method 
GET  http://localhost:5137/api/order/ HTTP/1.1
content-type: application/json

{

}


### Post Method 
POST http://localhost:5137/api/order/ HTTP/1.1
Content-Type: application/json

{
  "userId": "004dfc64-4316-4339-bdfb-30ce9d1fcd4a",
  "totalPrice": 21,
  "orderDetails": [
    {
      "productId": "d9e29dd2-c3e5-4750-8440-7428f286d26a",
      "quantity": 20
    }

  ]
}


### Delete Method 
POST http://localhost:5137/api/order/41e8979a-fbba-4d72-99a5-26711d6107db HTTP/1.1
Content-Type: application/json

{

}