### Get Method 
GET  http://localhost:5137/api/order/ HTTP/1.1
content-type: application/json

{

  
}


### Post Method 
POST http://localhost:5137/api/order/ HTTP/1.1
Content-Type: application/json

{
  "userId": "a453a349-dc12-4833-af64-1bc7c8c048aa",
  "totalPrice": 21,
  "orderDetails": [
    {
      "productId": "5f2db1f6-1a64-4630-bc81-965cb5951ba1",
      "quantity": 1
    },
        {
      "productId": "5f2db1f6-1a64-4630-bc81-965cb5951ba1",
      "quantity": 2
    },
        {
      "productId": "5f2db1f6-1a64-4630-bc81-965cb5951ba1",
      "quantity": 1
    }
  ]
}