### Get Method 
GET  http://localhost:5137/api/product?Limit=10&Offset=0&CategoryId=89b8434b-d036-49f5-836b-5b3841be53c4&SortOrder=dsc HTTP/1.1
content-type: application/json

### Get one Method 
GET  http://localhost:5137/api/product/13cf534f-d5b5-468c-b513-2ef3e8cf92a1 HTTP/1.1
content-type: application/json


### Delete Method
DELETE   http://localhost:5137/api/product/1328f25a-50ef-4ead-996e-522e5e7141fa HTTP/1.1
content-type: application/json


### Post Method
POST http://localhost:5137/api/product/ HTTP/1.1
Content-Type: application/json

{
    "title": "Polo Shirt",
    "description": "Woven coats for winter",
    "price": 10,
    "quantity": 50,
    "CategoryId": "9fcd9811-33db-415f-ba15-527515a7495e",
    "images": 
    [
    { "imageUrl": "string"},
    { "imageUrl": "string"}
    ]
}



###  Method
PATCH  http://localhost:5137/api/product/5d5691f9-e2be-4d90-8c47-e1af1537d37e HTTP/1.1
Content-Type: application/json

{
    "title": "Jacket",
    "description": "Light coats for summer",
    "price": 20,
    "quantity": 40,
    "CategoryId": "14baeb3a-1248-43f3-b561-944de14d27c4",
    "images": 
    [
    { "imageUrl": "string"}
    ]
}