### Get Method 
GET  http://localhost:5137/api/product HTTP/1.1
content-type: application/json

{

}

### Get one Method 
GET  http://localhost:5137/api/product/758010ae-edfb-470e-9efb-96287ca0ccaf HTTP/1.1
content-type: application/json


### Delete Method
DELETE   http://localhost:5137/api/product/29153909-e769-4547-ae69-d30bfa0d288f HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1laWQiOiI1OTM1ODhkZS1kOWU4LTQyZmQtODMzOS01Yjg3MDYxMWI4NzYiLCJ1c2VySWQiOiI1OTM1ODhkZS1kOWU4LTQyZmQtODMzOS01Yjg3MDYxMWI4NzYiLCJyb2xlIjoiQWRtaW4iLCJuYmYiOjE3MDQwNTM3MDgsImV4cCI6MTcwNDIyNjUwOCwiaWF0IjoxNzA0MDUzNzA4LCJpc3MiOiJIYXNhbiIsImF1ZCI6Imh0dHBzOi8vam95ZGlwa2FuamlsYWwuY29tLyJ9.a8kqr-T__aQf27RuBS098GQQolaVAoimUvp4RTVUnD4


### Post Method
POST http://localhost:5137/api/product/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1laWQiOiI1NTQwZmUwOS1iMzI0LTQyNTYtYTVhYy0zNTY2NGUxYWMyMTQiLCJ1c2VySWQiOiI1NTQwZmUwOS1iMzI0LTQyNTYtYTVhYy0zNTY2NGUxYWMyMTQiLCJyb2xlIjoiQWRtaW4iLCJuYmYiOjE3MDQwNTU3MTMsImV4cCI6MTcwNDIyODUxMywiaWF0IjoxNzA0MDU1NzEzLCJpc3MiOiJIYXNhbiIsImF1ZCI6Imh0dHBzOi8vam95ZGlwa2FuamlsYWwuY29tLyJ9.BJh5kPxCij-ss6TPqRBfI1pHlD58FTHJdCebeAQFDXI
 
{
    "title": "Jordan True Flight",
    "description": "Nothing as fly, nothing as comfortable, nothing as proven. The Air Max 90 stays true to its running roots with the iconic Waffle sole, stitched overlays and classic details. A bold, dark colourway contrasts with a gum outsole and reflective design details for a sleek look while Max Air cushioning adds comfort to your journey.",
    "price": 350,
    "quantity": 2000,
    "categoryId": "693eb135-2fee-4604-8049-a30b527c1e70",
    "images": 
    [
    { "imageUrl": "https://static.nike.com/a/images/t_PDP_864_v1,f_auto,q_auto:eco/u_126ab356-44d8-4a06-89b4-fcdcc8df0245,c_scale,fl_relative,w_1.0,h_1.0,fl_layer_apply/298fb136-14b0-45cf-9c66-b3654c67ef62/jordan-one-take-5-shoes-CQ0GM8.png"},
    { "imageUrl": "https://static.nike.com/a/images/t_PDP_864_v1,f_auto,q_auto:eco/u_126ab356-44d8-4a06-89b4-fcdcc8df0245,c_scale,fl_relative,w_1.0,h_1.0,fl_layer_apply/298fb136-14b0-45cf-9c66-b3654c67ef62/jordan-one-take-5-shoes-CQ0GM8.png"},
    { "imageUrl": "https://static.nike.com/a/images/t_PDP_864_v1,f_auto,q_auto:eco/u_126ab356-44d8-4a06-89b4-fcdcc8df0245,c_scale,fl_relative,w_1.0,h_1.0,fl_layer_apply/298fb136-14b0-45cf-9c66-b3654c67ef62/jordan-one-take-5-shoes-CQ0GM8.png"}
    ]
}



###  Method
PATCH  http://localhost:5137/api/product/758010ae-edfb-470e-9efb-96287ca0ccaf HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1laWQiOiI1OTM1ODhkZS1kOWU4LTQyZmQtODMzOS01Yjg3MDYxMWI4NzYiLCJ1c2VySWQiOiI1OTM1ODhkZS1kOWU4LTQyZmQtODMzOS01Yjg3MDYxMWI4NzYiLCJyb2xlIjoiQWRtaW4iLCJuYmYiOjE3MDQwNTM3MDgsImV4cCI6MTcwNDIyNjUwOCwiaWF0IjoxNzA0MDUzNzA4LCJpc3MiOiJIYXNhbiIsImF1ZCI6Imh0dHBzOi8vam95ZGlwa2FuamlsYWwuY29tLyJ9.a8kqr-T__aQf27RuBS098GQQolaVAoimUvp4RTVUnD4

{
    "title": "AIR MAX ALPHA TRAINER 11",
    "description": "Step into the future of athletic excellence with the Nike AirStride 2023, a groundbreaking fusion of cutting-edge technology and sleek design. Crafted for the modern athlete who demands both performance and style, these shoes are your ticket to superior comfort and unstoppable confidence.",
    "price": 100,
    "quantity": 60,
    "CategoryId": "cf1796e3-50c1-427c-a09b-2ee714353c29",
    "images": 
    [
    { "imageUrl": "https://img01.ztat.net/article/spp-media-p1/f7538b3b560a4e97a608553437388282/f15fe8ecb381410189d3fe7ef62f1960.jpg?imwidth=1800"},
    { "imageUrl": "https://img01.ztat.net/article/spp-media-p1/f7538b3b560a4e97a608553437388282/f15fe8ecb381410189d3fe7ef62f1960.jpg?imwidth=1800"},
    { "imageUrl": "https://img01.ztat.net/article/spp-media-p1/f7538b3b560a4e97a608553437388282/f15fe8ecb381410189d3fe7ef62f1960.jpg?imwidth=1800"}
    ]
}

