### Post Method 
POST http://localhost:5137/api/review/ HTTP/1.1
Content-Type: application/json

{
  "content": "this is a another  very very good review",
  "ratings": 4,
  "ProductId":"abb6fcea-1c2e-42e6-a927-e9ab49960ef4",
  "UserId": "004d51a4-fbae-44fb-b687-da4019e8d7c6"
}


###
DELETE  http://localhost:5137/api/review/571928b6-d482-4911-9fd8-8aedfde0beba HTTP/1.1
Content-Type: application/json