### Get Method 
GET  http://localhost:5137/api/user/ HTTP/1.1
content-type: application/json

### Get Method 
GET  http://localhost:5137/api/user/2718ffd0-9f1a-4303-ad2e-78301fbaf64a HTTP/1.1
content-type: application/json

### Post Method
POST http://localhost:5137/api/user/ HTTP/1.1
Content-Type: application/json

{
    "firstName": "Ilhaan",
    "lastName": "edge",
    "email": "illhaanl@gmail.com",
    "password": "nokia6300",
    "avatar": "https://yt3.googleusercontent.com",
    "address": "otavantie 20 a 15",
    "zip": "01450",
    "city": "vantaa"
}

### Delete method 
DELETE   http://localhost:5137/api/user/2718ffd0-9f1a-4303-ad2e-78301fbaf64a HTTP/1.1
content-type: application/json


### Update method 
PATCH   http://localhost:5137/api/user/2718ffd0-9f1a-4303-ad2e-78301fbaf64a HTTP/1.1
Content-Type: application/json

{
    "firstName": "ilhaan",
    "lastName": "hasan",
    "email": "hasssan@email.com",
    "password": "nokia6300",
    "avatar": "https://yt3.googleusercontent.com",
    "address": "otavantie 20 a 15",
    "zip": "01xa550",
    "city": "vantxaa"
}


### Post Method
POST http://localhost:5137/api/auth HTTP/1.1
Content-Type: application/json

{
    "email": "asffminadss@dmail.com",
    "password": "nokia6300"
}