### Get Method 
GET  http://localhost:5137/api/user/ HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1laWQiOiI4MWRiNzFkMC1lZDNmLTQ4ZjMtOGRiZi01Mzk3MGQ3MjhjYjUiLCJ1c2VySWQiOiI4MWRiNzFkMC1lZDNmLTQ4ZjMtOGRiZi01Mzk3MGQ3MjhjYjUiLCJyb2xlIjoiQWRtaW4iLCJuYmYiOjE3MDM3NDA4ODEsImV4cCI6MTcwMzkxMzY4MSwiaWF0IjoxNzAzNzQwODgxLCJpc3MiOiJIYXNhbiIsImF1ZCI6Imh0dHBzOi8vam95ZGlwa2FuamlsYWwuY29tLyJ9.yMiaO4NvIxDACIW9gjfuWFFu2LNhgYoHP-gSaPeQVEU

### Get Method 
GET  http://localhost:5137/api/user/f58d84f0-b6bb-499f-b7d2-98796cc15e53 HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1laWQiOiI4MWRiNzFkMC1lZDNmLTQ4ZjMtOGRiZi01Mzk3MGQ3MjhjYjUiLCJ1c2VySWQiOiI4MWRiNzFkMC1lZDNmLTQ4ZjMtOGRiZi01Mzk3MGQ3MjhjYjUiLCJyb2xlIjoiQWRtaW4iLCJuYmYiOjE3MDM3NDA4ODEsImV4cCI6MTcwMzkxMzY4MSwiaWF0IjoxNzAzNzQwODgxLCJpc3MiOiJIYXNhbiIsImF1ZCI6Imh0dHBzOi8vam95ZGlwa2FuamlsYWwuY29tLyJ9.yMiaO4NvIxDACIW9gjfuWFFu2LNhgYoHP-gSaPeQVEU

### Post Method User
POST http://localhost:5137/api/user/ HTTP/1.1
Content-Type: application/json

{
    "firstName": "John",
    "lastName": "doe",
    "email": "John@gmail.com",
    "password": "nokia6300",
    "avatar": "https://assets-prd.ignimgs.com/2022/11/22/avatar-blogroll2-1669090391194.jpg",
    "address": "green street 20 a 15",
    "zip": "01450",
    "city": "vantaa",
    "role": "user"
}



### Post Method Admin
POST http://localhost:5137/api/user/ HTTP/1.1
Content-Type: application/json

{
    "firstName": "Ron",
    "lastName": "Doe",
    "email": "ron@gmail.com",
    "password": "nokia6300",
    "avatar": "https://assets-prd.ignimgs.com/2022/11/22/avatar-blogroll2-1669090391194.jpg",
    "address": "ogreen street 20 a 15",
    "zip": "01450",
    "city": "vantaa",
    "role": "admin"
}

### Delete method 
DELETE   http://localhost:5137/api/user/7fe8ad51-ba23-40e2-93d2-dadbab687ef4 HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1laWQiOiI4MWRiNzFkMC1lZDNmLTQ4ZjMtOGRiZi01Mzk3MGQ3MjhjYjUiLCJ1c2VySWQiOiI4MWRiNzFkMC1lZDNmLTQ4ZjMtOGRiZi01Mzk3MGQ3MjhjYjUiLCJyb2xlIjoiQWRtaW4iLCJuYmYiOjE3MDM3NDA4ODEsImV4cCI6MTcwMzkxMzY4MSwiaWF0IjoxNzAzNzQwODgxLCJpc3MiOiJIYXNhbiIsImF1ZCI6Imh0dHBzOi8vam95ZGlwa2FuamlsYWwuY29tLyJ9.yMiaO4NvIxDACIW9gjfuWFFu2LNhgYoHP-gSaPeQVEU


### Update method 
PATCH   http://localhost:5137/api/user/2718ffd0-9f1a-4303-ad2e-78301fbaf64a HTTP/1.1
Content-Type: application/json

{
    "firstName": "ilhaan",
    "lastName": "hasan",
    "email": "hasssan@email.com",
    "password": "nokia6300",
    "avatar": "https://assets-prd.ignimgs.com/2022/11/22/avatar-blogroll2-1669090391194.jpg",
    "address": "otavantie 20 a 15",
    "zip": "01xa550",
    "city": "vantxaa"
}


### Post Method User Login
POST http://localhost:5137/api/auth/login HTTP/1.1
Content-Type: application/json

{
    "email": "user@gmail.com",
    "password": "nokia6300"
}


### Post Method Admin Login
POST http://localhost:5137/api/auth/login HTTP/1.1
Content-Type: application/json

{
    "email": "hasan@gmail.com",
    "password": "nokia6300"
}