### Get Method 
GET  http://localhost:5137/api/category/ HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1laWQiOiIwZTE2YTNmOS0xMjVjLTQ3ODUtYjIwMS1kN2Y4NDdmMzMyNzEiLCJ1c2VySWQiOiIwZTE2YTNmOS0xMjVjLTQ3ODUtYjIwMS1kN2Y4NDdmMzMyNzEiLCJyb2xlIjoiQWRtaW4iLCJuYmYiOjE3MDMzNzQzMTIsImV4cCI6MTcwMzU0NzExMiwiaWF0IjoxNzAzMzc0MzEyLCJpc3MiOiJIYXNhbiIsImF1ZCI6Imh0dHBzOi8vam95ZGlwa2FuamlsYWwuY29tLyJ9.8zNbkm2nLfooWTG_Ov7DnzACimpuepOsGngHl0VL4-8


### Post Method 
POST http://localhost:5137/api/category/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1laWQiOiIwZTE2YTNmOS0xMjVjLTQ3ODUtYjIwMS1kN2Y4NDdmMzMyNzEiLCJ1c2VySWQiOiIwZTE2YTNmOS0xMjVjLTQ3ODUtYjIwMS1kN2Y4NDdmMzMyNzEiLCJyb2xlIjoiQWRtaW4iLCJuYmYiOjE3MDMzNzQzMTIsImV4cCI6MTcwMzU0NzExMiwiaWF0IjoxNzAzMzc0MzEyLCJpc3MiOiJIYXNhbiIsImF1ZCI6Imh0dHBzOi8vam95ZGlwa2FuamlsYWwuY29tLyJ9.8zNbkm2nLfooWTG_Ov7DnzACimpuepOsGngHl0VL4-8

{
    "name": "Men"
}


### Get One Method 
GET http://localhost:5137/api/category/89b8434b-d036-49f5-836b-5b3841be53c4 HTTP/1.1
Content-Type: application/json



### Delete Method 
DELETE  http://localhost:5137/api/category/05e2553e-cefb-48a6-917f-324cf7d2538a HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1laWQiOiIwZTE2YTNmOS0xMjVjLTQ3ODUtYjIwMS1kN2Y4NDdmMzMyNzEiLCJ1c2VySWQiOiIwZTE2YTNmOS0xMjVjLTQ3ODUtYjIwMS1kN2Y4NDdmMzMyNzEiLCJyb2xlIjoiQWRtaW4iLCJuYmYiOjE3MDMzNzQzMTIsImV4cCI6MTcwMzU0NzExMiwiaWF0IjoxNzAzMzc0MzEyLCJpc3MiOiJIYXNhbiIsImF1ZCI6Imh0dHBzOi8vam95ZGlwa2FuamlsYWwuY29tLyJ9.8zNbkm2nLfooWTG_Ov7DnzACimpuepOsGngHl0VL4-8



### Patch Method 
PUT  http://localhost:5137/api/category/c9a4c198-b17a-4006-b204-6d48f51c95dc HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1laWQiOiIwZTE2YTNmOS0xMjVjLTQ3ODUtYjIwMS1kN2Y4NDdmMzMyNzEiLCJ1c2VySWQiOiIwZTE2YTNmOS0xMjVjLTQ3ODUtYjIwMS1kN2Y4NDdmMzMyNzEiLCJyb2xlIjoiQWRtaW4iLCJuYmYiOjE3MDMzNzQzMTIsImV4cCI6MTcwMzU0NzExMiwiaWF0IjoxNzAzMzc0MzEyLCJpc3MiOiJIYXNhbiIsImF1ZCI6Imh0dHBzOi8vam95ZGlwa2FuamlsYWwuY29tLyJ9.8zNbkm2nLfooWTG_Ov7DnzACimpuepOsGngHl0VL4-8

{
    "name": "Shoe"
}