### Get Method 
GET  http://localhost:5137/api/order/ HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1laWQiOiIzY2E2N2MzZi0yZDk2LTQyMDgtYWZhMy0wNDc0YzQ1MTQ1ZmUiLCJ1c2VySWQiOiIzY2E2N2MzZi0yZDk2LTQyMDgtYWZhMy0wNDc0YzQ1MTQ1ZmUiLCJyb2xlIjoiQWRtaW4iLCJuYmYiOjE3MDM0MzA0NjksImV4cCI6MTcwMzYwMzI2OSwiaWF0IjoxNzAzNDMwNDY5LCJpc3MiOiJIYXNhbiIsImF1ZCI6Imh0dHBzOi8vam95ZGlwa2FuamlsYWwuY29tLyJ9.E4aR7je1WoKPaS6AwM9jsYSD_ShS5YR2lv_W7JOQA4I

{

}

### Get One Method 

GET  http://localhost:5137/api/order/389b2182-b8a3-4b6f-bcf5-4a1aef352c66 HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1laWQiOiI4ZWU2MzFiOC01NzRkLTRkYWYtODMyOS1iM2E3ZmJiOWIzM2IiLCJ1c2VySWQiOiI4ZWU2MzFiOC01NzRkLTRkYWYtODMyOS1iM2E3ZmJiOWIzM2IiLCJyb2xlIjoiVXNlciIsIm5iZiI6MTcwMzQzMDA5MCwiZXhwIjoxNzAzNjAyODkwLCJpYXQiOjE3MDM0MzAwOTAsImlzcyI6Ikhhc2FuIiwiYXVkIjoiaHR0cHM6Ly9qb3lkaXBrYW5qaWxhbC5jb20vIn0.BIsQUZJtJHMVVT1FM3bzvWgQwno5nCKR_julOaPlJuQ

{

}


### Post Method 
POST http://localhost:5137/api/order/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1laWQiOiI4ZTgxMGY3OC1jZDhhLTRhYjMtYjBkMS05ZmRkNTQ1Y2FkN2IiLCJ1c2VySWQiOiI4ZTgxMGY3OC1jZDhhLTRhYjMtYjBkMS05ZmRkNTQ1Y2FkN2IiLCJyb2xlIjoiVXNlciIsIm5iZiI6MTcwMzQzMTMwNSwiZXhwIjoxNzAzNjA0MTA1LCJpYXQiOjE3MDM0MzEzMDUsImlzcyI6Ikhhc2FuIiwiYXVkIjoiaHR0cHM6Ly9qb3lkaXBrYW5qaWxhbC5jb20vIn0.bMiVi3j3yFBnG5O6fd6MBFn0kvJinsMXm9mwhwIywMk

{
  "userId": "004d51a4-fbae-44fb-b687-da4019e8d7c6",
  "totalPrice": 21,
  "orderDetails": [
    {
      "productId": "abb6fcea-1c2e-42e6-a927-e9ab49960ef4",
      "quantity": 2
    }

  ]
}

### Delete Method 
DELETE  http://localhost:5137/api/order/1930ffd5-f740-4e04-a58d-81c0c8d3d702 HTTP/1.1
Content-Type: application/json

{


}