### Get Method 
GET  http://localhost:5137/api/product?Search=Shirt HTTP/1.1
content-type: application/json

{

}

### Get one Method 
GET  http://localhost:5137/api/product/75e9deab-30e3-4dd2-bee5-cc5df5b62b6c HTTP/1.1
content-type: application/json


### Delete Method
DELETE   http://localhost:5137/api/product/1328f25a-50ef-4ead-996e-522e5e7141fa HTTP/1.1
content-type: application/json


### Post Method
POST http://localhost:5137/api/product/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1laWQiOiIwZTE2YTNmOS0xMjVjLTQ3ODUtYjIwMS1kN2Y4NDdmMzMyNzEiLCJ1c2VySWQiOiIwZTE2YTNmOS0xMjVjLTQ3ODUtYjIwMS1kN2Y4NDdmMzMyNzEiLCJyb2xlIjoiQWRtaW4iLCJuYmYiOjE3MDMzNzQzMTIsImV4cCI6MTcwMzU0NzExMiwiaWF0IjoxNzAzMzc0MzEyLCJpc3MiOiJIYXNhbiIsImF1ZCI6Imh0dHBzOi8vam95ZGlwa2FuamlsYWwuY29tLyJ9.8zNbkm2nLfooWTG_Ov7DnzACimpuepOsGngHl0VL4-8

{
    "title": "Shirt",
    "description": "Woven coats for winter",
    "price": 10,
    "quantity": 50,
    "CategoryId": "6cd12efa-8c27-46df-bb24-1e9484376ce7",
    "images": 
    [
    { "imageUrl": "https://cdni.llbean.net/is/image/wim/520655_459_41?hei=1095&wid=950&resMode=sharp2&defaultImage=llbprod/520655_459_41"}
    ]
}



###  Method
PATCH  http://localhost:5137/api/product/468b9746-f573-4a0d-8dc9-0c5fb2d0ef67 HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1laWQiOiIwZTE2YTNmOS0xMjVjLTQ3ODUtYjIwMS1kN2Y4NDdmMzMyNzEiLCJ1c2VySWQiOiIwZTE2YTNmOS0xMjVjLTQ3ODUtYjIwMS1kN2Y4NDdmMzMyNzEiLCJyb2xlIjoiQWRtaW4iLCJuYmYiOjE3MDMzNzQzMTIsImV4cCI6MTcwMzU0NzExMiwiaWF0IjoxNzAzMzc0MzEyLCJpc3MiOiJIYXNhbiIsImF1ZCI6Imh0dHBzOi8vam95ZGlwa2FuamlsYWwuY29tLyJ9.8zNbkm2nLfooWTG_Ov7DnzACimpuepOsGngHl0VL4-8

{
    "title": "Polo T Shirt",
    "description": "Woven coats for winter",
    "price": 10,
    "quantity": 50,
    "CategoryId": "b5849463-04ce-47bb-9428-0ccf48030b64",
    "images": 
    [
    { "imageUrl": "string"},
    { "imageUrl": "string"}
    ]
}

