### Post Method 
POST http://localhost:5137/api/review/ HTTP/1.1
Content-Type: application/json

{
  "content": "this is a another  very very good review",
  "ratings": 5,
  "ProductId":"75e9deab-30e3-4dd2-bee5-cc5df5b62b6c",
  "UserId": "8cda8c0d-6be4-49f8-a668-91e05fe1f7b0"
}


###
DELETE  http://localhost:5137/api/review/571928b6-d482-4911-9fd8-8aedfde0beba HTTP/1.1
Content-Type: application/json