name: 'Run unit tests'
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  unit-test:
    name: unit-test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout GitHub repo
        uses: actions/checkout@v4
      - name: Print message
        run: echo "Testing started"
      - name: Run unit test
        run: dotnet test
